specVersion: "1.0.0"

name: "avalanche-subql-starter"
version: "0.0.1"
runner:
  node:
    name: "@subql/node-avalanche"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: "This project can be use as a starting point for developing your new Avalanche SubQuery project"
repository: "https://github.com/subquery/avalanche-subql-starter"

schema:
  file: "./schema.graphql"

network:
  endpoint: "https://avalanche.api.onfinality.io/public"
  # endpoint:  https://api.avax.network
  # endpoint:  https://api.avax-test.network
  chainId: "mainnet"
  subnet: "C"
  dictionary: https://api.subquery.network/sq/subquery/avalanche-dictionary

dataSources:
  - kind: avalanche/Runtime
    startBlock: 13325661
    options:
      # Must be a key of assets
      abi: BetaSimpleFlatLostWorld
      address: "0x848697c66a7161ed9c4b9be1f59b83fd11524bbd"
    assets:
      BetaSimpleFlatLostWorld:
        file: "./abis/BetaSimpleFlatLostWorld.json"
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleTransfer
          kind: avalanche/LogHandler
          filter:
            topics:
              - Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
